# BL40A2010 Introduction to IoT-Based Systems

## Assignment 6, 01.03.2021

### Author: Alex Beattie

**Prisoner's dilemma** is a standard example of a game analyzed in game theory that shows why two completely rational individuals might not cooperate, even if it appears that it is in their best interests to do so. It was originally framed by Merrill Flood and Melvin Dresher while working at RAND in 1950. Albert W. Tucker formalized the game with prison sentence rewards and named it "prisoner's dilemma", presenting it as follows:

"Two members of a criminal gang are arrested and imprisoned. Each prisoner is in solitary confinement with no means of communicating with the other. The prosecutors lack sufficient evidence to convict the pair on the principal charge, but they have enough to convict both on a lesser charge. Simultaneously, the prosecutors offer each prisoner a bargain. Each prisoner is given the opportunity either to betray the other by testifying that the other committed the crime, or to cooperate with the other by remaining silent. The possible outcomes are:

- If A and B each betray the other (not-cooperating to each other), each of them serves $z$ years in prison (payoff of $-z$)
- If A betrays B (not-cooperating with B) but B remains silent (cooperating with A), A will serve $y$ years in prison (payoff $-y$) and B will serve $w$ years  (payoff of $-w$).
- If B betrays A (not-cooperating with A) but A remains silent (cooperating with B), B will serve $y$ years in prison (payoff $-y$) and A will serve $w$ years  (payoff of $-w$).
- If A and B both remain silent, both of them will serve $x$ years in prison (payoff of $-x$)."

The payoff table is presented below. 

|       *         | $B$ cooperates  | $B$ not-cooperating   |
|----------------|:---------------:|--------------:|
| $A$ cooperates |  $A \rightarrow -x$   | $A\rightarrow -w$  |
|       *         |  $B\rightarrow -x$   | $B\rightarrow -y$  |
|               |                 |               |
| $A$ not-cooperating   |  $A\rightarrow -y$   | $A\rightarrow -z$  |
|           *     |  $B\rightarrow -w$   | $B\rightarrow -z$  |

**However, this is only a *Prisoner's Dilemma GAME* for A GIVEN RELATION between the years in prison (payoffs) as to be studied next.**

ps. Text adapted from [Wikipedia](https://en.wikipedia.org/wiki/Prisoner's_dilemma).

**(1) Consider the Prisoner's dilemma description given above.**

**(a) What is the relation between the payoffs values $x\geq 0$, $y\geq 0$, $w\geq 0$ and $z \geq 0$ so that the game can be classified as [Prisoner's Dilemma](https://en.wikipedia.org/wiki/Prisoner's_dilemma)?**

**(b) Verify the results (i.e., the proposed inequality) with numerical examples using [nashpy](https://nashpy.readthedocs.io/en/stable/index.html). Please provide one example when the inequality holds and one it does not (check my example for Dove and Hawyk game).**

*Answer:* To be a Prisoner's Dilema game:
- Both betraying each other is worse than both being cooperating, therefore:  x < z,
- When one player betrays and the other cooperates it is advantageous to the betrayer: y < x
- If the other player does not cooperate then not-cooperating will be advantageous for you cooperation: z < w,
- There shall be Nash equilibria when one player cooperates and the other betrays.

Putting all together:  y < x < z < w

In [1]:
#Verification with nashpy
#Installing a missing library
! pip install nashpy

In [3]:
import numpy as np
import nashpy as nash

### Test 1:  y < x < z < w


|         *       | $B$ cooperates  | $B$ not-cooperative    |
|----------------|:---------------:|--------------:|
| $A$ cooperates |  $A \rightarrow -1$   | $A \rightarrow -4$  |
|      *          |  $B \rightarrow -1$   | $B\rightarrow 0$  |
|                |                 |               |
| $A$ not-cooperative |  $A\rightarrow 0$      | $A\rightarrow -3$  |
|        *        |  $B\rightarrow -4$   | $B\rightarrow -3$  |


In [10]:
# Test 1 -> x=1, w=4, z=3 and y=0
A = [[-1, -4], [0, -3]]
B = [[-1, 0], [-4, -3]]
prisoner_dilema = nash.Game(A, B)
prisoner_dilema

Bi matrix game with payoff matrices:

Row player:
[[-1 -4]
 [ 0 -3]]

Column player:
[[-1  0]
 [-4 -3]]

In [11]:
eqs = prisoner_dilema.support_enumeration()
list(eqs)

[(array([0., 1.]), array([0., 1.]))]

This output gives the *mixed strategies Nash equilibria.*

- **First line:** Player A (first array) and B (second player) will both cooperate with probability $0$ and not cooperate with probability $1$;


This satisfies the condition of being a Prisoners Dilemma.

### Test 2: z > w

|         *       | $B$ cooperates  | $B$ not-cooperative    |
|----------------|:---------------:|--------------:|
| $A$ cooperative |  $A \rightarrow -1$   | $A \rightarrow -2$  |
|        *        |  $B \rightarrow -1$   | $B\rightarrow 0$  |
|                |                 |               |
| $A$ not-cooperative|  $A\rightarrow 0$      | $A\rightarrow -3$  |
|      *          |  $B\rightarrow -2$   | $B\rightarrow -3$  |



In [12]:
# Test 2 -> x=1, y=0, z=3 and w=2
A = [[-1, -2], [0, -3]]
B = [[-1, 0], [-2, -3]]
prisoner_dilema2 = nash.Game(A, B)
prisoner_dilema2

Bi matrix game with payoff matrices:

Row player:
[[-1 -2]
 [ 0 -3]]

Column player:
[[-1  0]
 [-2 -3]]

In [13]:
eqs = prisoner_dilema2.support_enumeration()
list(eqs)

[(array([1., 0.]), array([0., 1.])),
 (array([0., 1.]), array([1., 0.])),
 (array([0.5, 0.5]), array([0.5, 0.5]))]

This output gives the *mixed strategies Nash equilibria.*

- **First line:** Player A (first array) will be cooperative with probability $1$ and not-cooperative with probability $0$;
 Player B (second array) will be cooperative with probability $0$ and be timid with probability $1$.
- **Second line:** Player A (first array) will be cooperative with probability $0$ and be not cooperative with probability $1$;
 Player B (second array) will be cooperative with probability $1$ and be not cooperative with probability $0$.

This satisfies the condition of being a Prisoner's dileama. Note that there is also a third Nash equilibrium, but a mixed strategy one.
- **Third line:** Both players will be cooperative with probability $1/2$ and not-cooperative with probability $1/2$;

**(2) Justify why the game from the previous exercise is or is not a good (reasonable) model when $A$ and $B$ are:**

**1. Two trained members from the army when they are in prison.**

No. This is not a good model because the model does not account for any training. In the military part of the training presumably
includes not betraying your unit or fellow soldiers. So the game would be unlikely to predict the outcome of this situation

**2. Competitive companies in the market discussing standardization.**

Yes. Even though mutually agreed upon standardization could bring better benefits to both companies many companies choose
to develop and use proprietary standards. For example apple uses a proprietary connector for their phones and most laptop
computers have proprietry power supplies.

**3. Two different autonomous IoT-based home energy management algorithms that are focus on energy efficiency.**

No. Because these two systems are focused on energy efficiency there would be no benefit in betraying the other one. The
focous of these systems is ensuring energy is used as efficiently as possible, not maximizing their own ammount of energy.

**4. Two different autonomous IoT-based home energy management algorithms that are focus on profit maximization.**

Yes. When both systems are trying to maximize profit they will choose to betray the other if it involves financial gain
for one of the systems. This is one of the problems with profit-driven power distribution and energy grids.

**ps. You need to think about the assumption used in Game Theory and in the Prisoner's dilemma problem setting.**

